### ISSUE TITLE
In Getting Started page, add how to label specific columns with tags

### ISSUE THREAD

**Issue by adam-campbell-mfe** [infinitelambda/dbt-tags#11]
This is covered in the video at around 1:50 but is not in the getting started guide.   This is a nice tool, but it took me quite a while to figure that bit out.

**Comment by datnguye** [comment]
Thanks @adam-campbell-mfe for raising this! 
Glad that you found this tool useful 🙌 

Let me review and get back to you. 
But you’ll be more than welcome to create PR for it, please let me know today if that’s the case. Thanks 🙏

**Comment by il-dat** [comment]
Thanks @adam-campbell-mfe for raising this!
Glad that you found this tool useful 🙌

Let me review and get back to you.
But you’ll be more than welcome to create PR for it, please let me know today if that’s the case. Thanks 🙏

**Comment by il-dat** [comment]
FYI: This should be included in PR #12

**Comment by adam-campbell-mfe** [comment]
Thank you! Had a look and that makes a lot more sense.
