### ISSUE TITLE
Applying Tags on columns in source table

### ISSUE THREAD

**Issue by pramalingam2022** [infinitelambda/dbt-tags#15]
### Describe the feature

Applying Tags on columns in source table

### Describe alternatives you've considered

Often we would require to mask sensitive columns in source tables in Snowflake, for which it would be good if we could update teh source configs in DBT with appropriate tags on columns.

This will improve the usage and wider applicability of this package

**Comment by il-dat** [comment]
Thanks @pramalingam2022 that sounds a very good suggestion!

Are you interested in making a Pull Request for this? You will be more than welcome. If not, we will make it a go whenever having the good time 🤜🤛

**Comment by bsuryachandra** [comment]
I'm happy to contribute to this feature

**Comment by il-dat** [comment]
Thanks a lot for the contribution @bsuryachandra , and @thu-IL for the support of reviewing the changes

I've merged the PR and released it to v1.2.0 which should be soon available in the hub.
