### ISSUE TITLE
target.schema not included in path to tag when dbt_tags__opt_in_default_naming_config is false

### ISSUE THREAD

**Issue by CadenSenitteGit** [infinitelambda/dbt-tags#21]
### Describe the bug

There was a recent change to the second macro in the `get_resource_ns.sql` file.  There is a syntax issue with a parenthesis.  Within the `else` statement (when dbt_tags__opt_in_default_naming_config =  false), this is what is returned:

`{{ return(var("dbt_tags__database", target.database)) ~ "." ~ var("dbt_tags__schema", target.schema) }}`

The second parenthesis after target.database should be removed and added to the end of target.schema, so that the schema var is included in the return statement.  Should look like this:

`{{ return(var("dbt_tags__database", target.database) ~ "." ~ var("dbt_tags__schema", target.schema)) }}`

### Steps to reproduce

- In dbt_project.yml, set the var `dbt_tags__opt_in_default_naming_config: false`
- In dbt_project.yml, set a the vars for `dbt_tags__database` and `dbt_tags__schema` to desired values.
- Execute a dbt run or build

### Expected results

The tag is found at the specified target_database.target_schema

### Actual results

The tag cannot be found because the macro is looking for it in target.database, but not including the target.schema in the path.

### System information

**The contents of your `packages.yml` file:**

**Which database are you using dbt with?**

- [x ] snowflake
- [ ] other (specify: ____________)

**The output of `dbt --version`:**

```log
<output goes here>
```

### Additional context

The issue is line 9 of the get_resource_ns.sql file.  There was a recent [commit](https://github.com/infinitelambda/dbt-tags/commit/0f4a5452bce0de42c658f5c69f1dc91bde478cef) to that line that needs refactoring.  The parenthesis just needs to be moved to the end of target.schema so that the schema var is included in the return statement.

**Comment by il-dat** [comment]
Thanks @CadenSenitteGit for raising this bug!

This was my bad, it was too rushed yesterday so I made a fix incorrectly.
It should be fixed in v1.3.1 now - sorry for the inconvenience here!

**Comment by CadenSenitteGit** [comment]
@il-dat no worries, thank you for the fix, worked great today!
